# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
machine:
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
  java:
    version: openjdk7
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install packages and AWS CLI
          command: |
            yarn install
            sudo apt-get install awscli

      - run:
          name: Create test blog
          # For this to work we need to supply user and password or skip admin user creation
          command: bin/seehund create "Test blog ${CIRCLE_BUILD_NUM}" --create-admin-user=false

      - run:
          name: Run tests
          command: |
            eval $(bin/seehund env -b test-blog-${CIRCLE_BUILD_NUM})
            yarn test

      - run:
          name: Cleanup
          when: always
          command: bin/seehund destroy -b "test-blog-${CIRCLE_BUILD_NUM}"

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


